"""
Django settings for fbackend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import sentry_sdk


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
BASE_API_URL = os.getenv('BASE_API_URL')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS','localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')
API_KEY = os.getenv('API_KEY')


# Celery settings
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0' 

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_RESULT_EXPIRES = 3600  



CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'




CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_celery_beat',
    #app
    'football',
    'blog',
    'pages',
    'prediction',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'football.context_processors.fixture_carousel',
            ],
        },
    },
]

WSGI_APPLICATION = 'fbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = BASE_DIR / 'media'

# Media storage — Cloudflare R2
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.getenv('R2_ACCESS_KEY_ID'),
                "secret_key": os.getenv('R2_SECRET_ACCESS_KEY'),
                "bucket_name": os.getenv('R2_BUCKET_NAME'),
                "endpoint_url": os.getenv('R2_ENDPOINT_URL'),
                "file_overwrite": False,
                "querystring_auth": False,
                "custom_domain": "media.footiestat.com",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = os.getenv('R2_PUBLIC_URL') + '/'
else:
    MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


sentry_sdk.init(
    dsn="https://24793e4b4a3749a228d01c86f1fc4217@o4511178783653888.ingest.de.sentry.io/4511178786340944",
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)





DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration — replace with real SMTP credentials in production
#EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
#EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
#EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
#EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
#EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
#EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
#DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'FootieStat <noreply@footiestat.com>')
#CONTACT_EMAIL = os.getenv('CONTACT_EMAIL', EMAIL_HOST_USER)

# Security settings — only enforce HTTPS in production
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prediction app settings
PREDICTION_MIN_FIXTURES = int(os.getenv("PREDICTION_MIN_FIXTURES", 8))
PREDICTION_MIN_MONSTER_FIXTURES = int(os.getenv("PREDICTION_MIN_MONSTER_FIXTURES", 20))
PREDICTION_MONSTER_DAYS_AHEAD = int(os.getenv("PREDICTION_MONSTER_DAYS_AHEAD", 7))
PREDICTION_PRIORITY_THRESHOLD = int(os.getenv("PREDICTION_PRIORITY_THRESHOLD", 20))
PREDICTION_CACHE_TTL_PREDICTIONS = int(os.getenv("PREDICTION_CACHE_TTL_PREDICTIONS", 14400))
PREDICTION_CACHE_TTL_ODDS = int(os.getenv("PREDICTION_CACHE_TTL_ODDS", 7200))
PREDICTION_CACHE_TTL_CLAUDE = int(os.getenv("PREDICTION_CACHE_TTL_CLAUDE", 21600))
PREDICTION_CACHE_TTL_SMALL = int(os.getenv("PREDICTION_CACHE_TTL_SMALL", 10800))
PREDICTION_CACHE_TTL_MONSTER = int(os.getenv("PREDICTION_CACHE_TTL_MONSTER", 21600))
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
