# Generated by Django 5.2 on 2025-06-01 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_team_national'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='head_to_head_snapshot',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='snapshot_processed',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='HeadToHeadMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_fixture_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('league_name', models.CharField(max_length=100)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_away_matches', to='football.team')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_matches', to='football.fixture')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_home_matches', to='football.team')),
            ],
            options={
                'verbose_name': 'Head to Head Match',
                'verbose_name_plural': 'Head to Head Matches',
                'ordering': ['-date'],
            },
        ),
    ]
