# Generated by Django 5.2 on 2025-06-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_remove_fixture_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headtoheadmatch',
            old_name='away_goals',
            new_name='away_extra_time_goals',
        ),
        migrations.RenameField(
            model_name='headtoheadmatch',
            old_name='home_goals',
            new_name='away_fulltime_goals',
        ),
        migrations.RemoveField(
            model_name='headtoheadmatch',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='headtoheadmatch',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='teamformsnapshot',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='teamformsnapshot',
            name='goals_for',
        ),
        migrations.RemoveField(
            model_name='teamformsnapshot',
            name='league',
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='away_half_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='away_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='away_penalty_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='home_extra_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='home_fulltime_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='home_half_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='home_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headtoheadmatch',
            name='home_penalty_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='away_extra_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='away_fulltime_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='away_half_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='away_penalty_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='home_extra_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='home_fulltime_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='home_half_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='home_penalty_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='league_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='league_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
