# Generated by Django 5.2 on 2025-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_rename_away_goals_headtoheadmatch_away_extra_time_goals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamformsnapshot',
            old_name='opponent_id',
            new_name='opponent',
        ),
        migrations.RemoveField(
            model_name='teamformsnapshot',
            name='matchday',
        ),
        migrations.AddField(
            model_name='teamformsnapshot',
            name='round_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamformsnapshot',
            name='match_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='teamformsnapshot',
            name='result',
            field=models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw')], max_length=5, null=True),
        ),
    ]
