# Generated by Django 5.2 on 2026-02-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_rename_opponent_id_teamformsnapshot_opponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureIngestion',
            fields=[
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ingestion', serialize=False, to='football.fixture')),
                ('needs_h2h', models.BooleanField(default=True)),
                ('needs_form', models.BooleanField(default=True)),
                ('needs_standings', models.BooleanField(default=True)),
                ('needs_advanced_stats', models.BooleanField(default=True)),
                ('h2h_processed_at', models.DateTimeField(blank=True, null=True)),
                ('form_processed_at', models.DateTimeField(blank=True, null=True)),
                ('standings_processed_at', models.DateTimeField(blank=True, null=True)),
                ('advanced_stats_processed_at', models.DateTimeField(blank=True, null=True)),
                ('h2h_retry_count', models.IntegerField(default=0)),
                ('form_retry_count', models.IntegerField(default=0)),
                ('standings_retry_count', models.IntegerField(default=0)),
                ('advanced_stats_retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('is_fully_processed', models.BooleanField(db_index=True, default=False)),
                ('fully_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['needs_h2h', 'h2h_retry_count'], name='football_fi_needs_h_f27f84_idx'), models.Index(fields=['needs_form', 'form_retry_count'], name='football_fi_needs_f_5f7a2b_idx'), models.Index(fields=['needs_standings', 'standings_retry_count'], name='football_fi_needs_s_369b8a_idx'), models.Index(fields=['needs_advanced_stats'], name='football_fi_needs_a_214721_idx'), models.Index(fields=['is_fully_processed'], name='football_fi_is_full_b9ede1_idx')],
            },
        ),
    ]
