# Generated by Django 5.2 on 2026-02-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_fixtureingestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureAdvancedStats',
            fields=[
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='advanced_stats', serialize=False, to='football.fixture')),
                ('home_last_5_form', models.JSONField(default=list, help_text='Last 5 matches overall')),
                ('home_last_5_home_form', models.JSONField(default=list, help_text='Last 5 home matches only')),
                ('home_last_5_vs_similar_rank', models.JSONField(default=list, help_text="Last 5 vs teams near opponent's rank (±3 positions)")),
                ('home_wins_last_5', models.PositiveSmallIntegerField(default=0)),
                ('home_draws_last_5', models.PositiveSmallIntegerField(default=0)),
                ('home_losses_last_5', models.PositiveSmallIntegerField(default=0)),
                ('home_goals_scored_last_5', models.PositiveSmallIntegerField(default=0)),
                ('home_goals_conceded_last_5', models.PositiveSmallIntegerField(default=0)),
                ('home_home_wins_last_5', models.PositiveSmallIntegerField(default=0)),
                ('home_home_draws_last_5', models.PositiveSmallIntegerField(default=0)),
                ('home_home_losses_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_last_5_form', models.JSONField(default=list, help_text='Last 5 matches overall')),
                ('away_last_5_away_form', models.JSONField(default=list, help_text='Last 5 away matches only')),
                ('away_last_5_vs_similar_rank', models.JSONField(default=list, help_text="Last 5 vs teams near opponent's rank (±3 positions)")),
                ('away_wins_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_draws_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_losses_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_goals_scored_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_goals_conceded_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_away_wins_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_away_draws_last_5', models.PositiveSmallIntegerField(default=0)),
                ('away_away_losses_last_5', models.PositiveSmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fixture Advanced Stats',
                'verbose_name_plural': 'Fixture Advanced Stats',
            },
        ),
    ]
