# Generated by Django 5.2 on 2026-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_fixtureadvancedstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headtoheadmatch',
            options={'ordering': ['fixture', '-date'], 'verbose_name': 'Head to Head Match', 'verbose_name_plural': 'Head to Head Matches'},
        ),
        migrations.AlterModelOptions(
            name='teamformsnapshot',
            options={'ordering': ['team', '-match_date']},
        ),
        migrations.AlterField(
            model_name='teamformsnapshot',
            name='fixture_id',
            field=models.BigIntegerField(),
        ),
    ]
