# Generated by Django 5.2 on 2026-03-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_alter_headtoheadmatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureingestion',
            name='detailed_stats_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixtureingestion',
            name='detailed_stats_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixtureingestion',
            name='needs_detailed_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FixtureStatistics',
            fields=[
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detailed_stats', serialize=False, to='football.fixture')),
                ('home_team_id', models.PositiveIntegerField()),
                ('home_team_name', models.CharField(max_length=100)),
                ('home_shots_on_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_shots_off_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_total_shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_blocked_shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_shots_insidebox', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_shots_outsidebox', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_fouls', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_corner_kicks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_offsides', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_ball_possession', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_yellow_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_red_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_goalkeeper_saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_total_passes', models.PositiveIntegerField(blank=True, null=True)),
                ('home_passes_accurate', models.PositiveIntegerField(blank=True, null=True)),
                ('home_passes_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_expected_goals', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('home_goals_prevented', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_team_id', models.PositiveIntegerField()),
                ('away_team_name', models.CharField(max_length=100)),
                ('away_shots_on_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_shots_off_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_total_shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_blocked_shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_shots_insidebox', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_shots_outsidebox', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_fouls', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_corner_kicks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_offsides', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_ball_possession', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_yellow_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_red_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_goalkeeper_saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_total_passes', models.PositiveIntegerField(blank=True, null=True)),
                ('away_passes_accurate', models.PositiveIntegerField(blank=True, null=True)),
                ('away_passes_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_expected_goals', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_goals_prevented', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['processed_at'], name='football_fi_process_d30033_idx')],
            },
        ),
    ]
