# Generated by Django 5.2 on 2026-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_fixtureingestion_detailed_stats_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturestatistics',
            name='match_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
