# Generated by Django 5.2 on 2026-03-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_fixturestatistics_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_extratime_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_fulltime_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_extratime_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_fulltime_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_halftime_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
