# Generated by Django 5.2 on 2026-03-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_fixturestatistics_away_extratime_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='away_extratime_score',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='away_fulltime_score',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='away_goals',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='away_halftime_score',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='away_penalty_score',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='home_extratime_score',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='home_fulltime_score',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='home_goals',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='home_halftime_score',
        ),
        migrations.RemoveField(
            model_name='fixturestatistics',
            name='home_penalty_score',
        ),
    ]
