# Generated by Django 5.2 on 2026-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_remove_fixturestatistics_away_extratime_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_extra_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_fulltime_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_half_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='away_penalty_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_extra_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_fulltime_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_half_time_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturestatistics',
            name='home_penalty_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
