# Generated by Django 5.2 on 2026-03-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_fixturestatistics_away_extra_time_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturestatistics',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
