# Generated by Django 5.2 on 2026-03-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_fixturestatistics_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AddField(
            model_name='league',
            name='priority',
            field=models.PositiveSmallIntegerField(default=999, help_text='Lower number = higher priority. 1-10 for top leagues, 999 for others'),
        ),
    ]
