# Generated by Django 5.2 on 2026-03-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_alter_league_options_league_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixtureingestion',
            options={'ordering': ['fixture__date', 'fixture__id']},
        ),
    ]
