# Generated by Django 5.2 on 2026-03-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_alter_fixtureingestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturestatistics',
            name='away_goals_prevented',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixturestatistics',
            name='home_goals_prevented',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
