# Generated by Django 5.2 on 2026-03-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_alter_fixturestatistics_away_goals_prevented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturestatistics',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_stats', to='football.fixture'),
        ),
        migrations.AlterField(
            model_name='fixturestatistics',
            name='match_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='fixturestatistics',
            index=models.Index(fields=['fixture'], name='football_fi_fixture_86b2d4_idx'),
        ),
    ]
