# Generated by Django 4.2 on 2026-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_fixture_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
