# Generated by Django 5.2 on 2026-03-18 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('article_type', models.CharField(choices=[('match_preview', 'Match Preview'), ('match_report', 'Match Report'), ('analysis', 'Tactical Analysis'), ('news', 'Breaking News'), ('interview', 'Interview'), ('opinion', 'Opinion Piece'), ('feature', 'Feature Story')], default='news', max_length=20)),
                ('image_1', models.URLField(blank=True, help_text='Primary image', null=True)),
                ('image_2', models.URLField(blank=True, help_text='Secondary image (optional)', null=True)),
                ('excerpt', models.TextField(help_text='Brief summary for previews', max_length=300)),
                ('content', models.TextField(help_text='Full article content (supports HTML)')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.IntegerField(default=5, help_text='Reading time in minutes')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='blog_articl_publish_d755f3_idx'), models.Index(fields=['-view_count'], name='blog_articl_view_co_946ccd_idx'), models.Index(fields=['article_type'], name='blog_articl_article_be76b7_idx'), models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'), models.Index(fields=['is_published'], name='blog_articl_is_publ_0f077c_idx')],
            },
        ),
    ]
