# Generated by Django 5.2 on 2026-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Primary image', null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Secondary image (optional)', null=True, upload_to='articles/'),
        ),
    ]
